name: Template action

on:
  issues:
    types: [labeled]

jobs:
  close-issues:
    name: "Close issues that don't follow a template"

    runs-on: ubuntu-latest

    steps:
      - uses: mhmdanas/action-template@v0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          type: comment
